config/routes.rb
Rails.application.routes.draw do
  root "cpf#index"
  resources :cpf, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cpf.rb
# frozen_string_literal: true
require 'cpf_cnpj'
include PgSearch::Model

class Cpf < ApplicationRecord
  before_validation :format_cpf
  validates :cpf, uniqueness: true, presence: true
  validate :validate_cpf
  validate :cpf_exists
  pg_search_scope :search_by_cpf,
                  against: [:cpf],
                  using: {
                    tsearch: { threshold: 0.3 }
                  }

  private

  def cpf_exists
    if Cpf.where(cpf: cpf).exists?
      errors.add(:cpf, "ExistsCpfException")
    end
  end

  def validate_cpf
    errors.add(:cpf, 'InvalidCpfException') unless valid_cpf?(cpf)
  end

  def valid_cpf?(cpf)
    CPF.valid?(cpf)
  end

  def format_cpf
    self.cpf = cpf_formatted if cpf.present?
  end

  def cpf_formatted
    cpf.gsub(/\D/, '') if cpf
  end
  def self.search_by_cpf(query)
    where(cpf: query.gsub(/\D/, ''))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cpf_controller.rb
# frozen_string_literal: true
require 'cpf_cnpj'

class CpfController < ApplicationController

  def index
    if params[:query].present?
      if valid_cpf?(params[:query])
        @cpfs = Cpf.search_by_cpf(params[:query])
        respond_to do |format|
          format.turbo_stream { render turbo_stream: turbo_stream.replace('_top', partial: 'cpf_list') }
          format.html
        end
      else
        flash[:notice] = 'InvalidCpfException'
        respond_to do |format|
          format.turbo_stream { render turbo_stream: turbo_stream.replace('_top', partial: 'cpf_list') }
          format.html
        end
      end
    else
      flash[:notice] = 'NotFoundCpfException'
      @cpfs = Cpf.distinct
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace('_top', partial: 'cpf_list') }
        format.html
      end
    end
  end

  def show
    @cpf = Cpf.find(params[:id])
  end

  def new
    @cpf = Cpf.new
  end

  def create
    @cpf = Cpf.new(cpf_params)
    respond_to do |format|
      if @cpf.save
        index
      else
        @cpf.cpf = ''
        format.turbo_stream { render turbo_stream: turbo_stream.replace('create_cpf', partial: 'cpf'  ) }
      end

    end
  end

  def delete
  end

  private
  def valid_cpf?(cpf)
    CPF.valid?(cpf)
  end

  def cpf_params
    params.require(:cpf).permit(:cpf)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Heroicon::Engine.helpers


  def field_error_message(object, attribute, custom_css_class = "text-rose-600")
    error_messages = object&.errors&.full_messages_for(attribute)
    return ''.html_safe if error_messages.blank?
    error_message = error_messages.first.gsub("#{attribute.to_s.humanize} ", "")
    "<p class=\"#{custom_css_class}\">#{error_message}</p>".html_safe
    end
end

app/views/cpf/_cpf.html.erb
<%= turbo_frame_tag :create_cpf do %>
  <%= form_with(model: @cpf, url: cpf_index_path(@cpf)) do |form| %>
    <div class="mb-4">
      <%= form.label :cpf, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_field :cpf, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>
    <div class="flex items-center justify-between">
      <%= form.submit class: "bg-blue-500 cursor-pointer hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>

    <% if @cpf.errors.any? %>
      <div class="text-red-500">
        <% @cpf.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <% end %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/cpf/_cpf_list.html.erb
<% @cpfs.each do |cpf_record|%>
    <div class="mb-4">
        <%= cpf_record.cpf %>
    </div>
<% end %>

app/views/cpf/index.html.erb
<div class="flex-auto justify-center rounded-lg px-2 py-2 bg-gray-100 max-w-screen-sm shadow-md">
  <div class="rounded-lg items-center py-2 px-2 mt-2">
    <%= form_with url: root_path, method: :get, data: { turbo_frame: 'list_cpf' }, local: true do |f| %>
      <%= f.text_field :query, value: params[:query], placeholder: "Search by CPF number", class: "border-gray-400 rounded-lg bg-white w-96 px-4 py-2", style: "width: 500px; border-width: 2px;" %>
      <button type="submit" class="ml-2 rounded-lg bg-blue-800 px-4 py-2 text-white">Search</button>
    <% end %>
  </div>
</div>


<%= render 'cpf_list'%>

app/views/cpf/new.html.erb
<%= render 'cpf' %>

app/views/cpf/show.html.erb
<%= @cpf.cpf %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FOOd</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<main>
  <%= turbo_frame_tag :_top do %>
    <%= yield %>
  <% end %>
</main>
</body>
</html>